### ISSUE TITLE
Bug on hovering image

### ISSUE THREAD

**Issue by mauriciosoares** [i-like-robots/EasyZoom#61]
Hey man, great work on the plugin :)

I know that in the plugin's site it is working flawlessly, but when I used the plugin I had to do a couple of things on your CSS:

```css
.easyzoom-flyout {
	position:absolute;
	z-index: 100;
	overflow: hidden;
	background: #FFF;
    /* added all below */
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}
```

For some reason, this div was below the container of the smaller image, with no width neither height, and with overflow hidden. and since the image inside `.easyzoom-flyout` had a `absolute` position, it was not appearing.

I know it's probably something in the structure of my website, but just to make sure you are aware of it :)

Ah, I was using the inside style of the plugin (appearing the image over the smaller image).
